Don't symlink the PHPUnit Uninstall xml config
It may be causing issues on PHP 5.2:

```
Fatal error: Uncaught exception 'PHPUnit_Framework_Exception' with message 'Neither ".php" nor ".php" could be opened.' in /home/travis/.phpenv/versions/5.2.17/pear/PHPUnit/Util/Skeleton/Test.php:100

Stack trace:
#0 /home/travis/.phpenv/versions/5.2.17/pear/PHPUnit/TextUI/Command.php(157): PHPUnit_Util_Skeleton_Test->__construct('', '')
#1 /home/travis/.phpenv/versions/5.2.17/pear/PHPUnit/TextUI/Command.php(130): PHPUnit_TextUI_Command->run(Array, true)
#2 /home/travis/.phpenv/versions/5.2.17/bin/phpunit(46): PHPUnit_TextUI_Command::main()
#3 {main}
  thrown in /home/travis/.phpenv/versions/5.2.17/pear/PHPUnit/Util/Skeleton/Test.php on line 100
```